language: node_js
node_js:
  - 0.10
  - 0.12
  - iojs
branches:
  only:
    - test
    - active
    - master
install:
  - ./install.sh
notifications:
  email:
    recipients:
      - om@soundsapiens.com
    on_success: change
    on_failure: always
