language: node_js
node_js:
  - 0.10
branches:
  only:
    - test
    - active
    - master
install:
  - npm install
  - npm install -g batshit gulp
  - cd test && npm install
  - cd ..
  - node -e "console.log('the tmp dir is:', require('os').tmpdir())"
notifications:
  email:
    recipients:
      - om@soundsapiens.com
    on_success: change
    on_failure: always
